export const ActionTypes = { 
    SET_DATA: "SET_DATA",
    SET_REQUEST_PARAMS: "SET_REQUEST_PARAMS",
    SET_LOADING: "SET_LOADING",
    SET_SELECTED_METHOD: "SET_SELECTED_METHOD",
    SET_ADD_TO_HISTORY: "ADD_TO_HISTORY",
    SET_URL_IN_FORM: "SET_URL",
    SET_METHOD_IN_FORM:"SET_METHOD_IN_FORM"
    
  };
  